apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: 62fcb4ff-eccd-4f22-9b6d-6befb26254fa
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
